### ISSUE TITLE
Speedup builds by caching data [8h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-elm-starter#103]
We could benefit from [caching](https://docs.travis-ci.com/user/caching/#Enabling-multiple-caching-features) `node_modules`, and Drupal's contrib modules.

The way I imagine this is we hold a checksum of `package.json` and of `drupal.make` -- so if it changes we'll know to invalidate the cache.

This will probably mean that in our docker we should be able to mount the content of `node_modules` and `www/profiles/../modules|themes` from Travis.

@AronNovak 6h sounds ok to you?

**Comment by AronNovak** [comment]
@amitaibu Yes, the timebox seems to be realistic. The longer part will be to test the scenarios when the cache is not valid anymore.

**Comment by amitaibu** [comment]
@AronNovak not high priority, but defiantly a nice to have

**Comment by AronNovak** [comment]
The current approximate performance of the builds:
![perf](https://cloud.githubusercontent.com/assets/114076/25997474/723dae56-371c-11e7-8db9-89033c241f75.png)

**Comment by amitaibu** [comment]
Bumped by 2h.

**Comment by AronNovak** [comment]
Post PR execution times:
![pdf1](https://cloud.githubusercontent.com/assets/114076/26624803/569dc052-45f2-11e7-80d4-aafb9a005c66.png)

**Comment by AronNovak** [comment]
So basically it's not really possible to measure the benefit of the caching for now, thinking about further possibilities.
