### ISSUE TITLE
Make Travis pass on master [2h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/drupal-elm-starter#125]
see #124  , master does not pass anymore, almost certainly due to https://hub.docker.com/r/gizra/drupal-lamp/builds/bkeaacyagu8vbipgwo2n4pf/

**Comment by AronNovak** [comment]
What's strange that with identical local Docker images, this `gulp-utils` error does not happen, the WDIO tests are started.
What I will try to skip global `gulp` from the game.

**Comment by AronNovak** [comment]
@amitaibu I'd like to ask you help as i have the feeling that it's not efficient to proceed.
This Travis failure is almost certainly due to the upgrade of the Docker image:
https://hub.docker.com/r/gizra/drupal-lamp/builds/bkeaacyagu8vbipgwo2n4pf/
An easy fix is to revert that and forget about frontend tools embedded in the Docker image.

After https://github.com/Gizra/drupal-elm-starter/pull/118#issuecomment-310090322 , i could make it work without `sudo`, but I could not see a big improvement of the execution time. The opposite direction could be to make the image lighter, dropping Solr (are there any projects out there that uses the built-in Solr from that Docker image?)

So I ask your opinion if I should fight more to make everything work with WDIO, global gulp, etc embedded into Docker or we revert something and seeks for other directions.

**Comment by amitaibu** [comment]
> An easy fix is to revert that and forget about frontend tools embedded in the Docker image.

👍
