### ISSUE TITLE
Make Elm Test execution sleeker via npm [3h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/drupal-elm-starter#136]
`elm-test src/elm/TestRunner.elm`

could become

`npm test`

And we could install the test execution dependencies straight from `packages.json`.

**Comment by bitamar** [comment]
When I `elm-test src/elm/TestRunner.elm` from the `client/` dir, I get: 
```
It looks like you're running elm-test from within your tests directory.

Please run elm-test from your project's root directory, where its elm-package.json lives!
```
Do you know what might be the reason? This error doesn't make sense to me, as that's where elm-package.json is.

**Comment by amitaibu** [comment]
Yeah, your elm-test is a higher version that the one we use here.

@AronNovak we should probably add elm-test to `package.json` and upon `npm test` call the local one.

**Comment by AronNovak** [comment]
@amitaibu Agreed, `npm test` would be nice, but it would require a boost of that thin timebox.

**Comment by amitaibu** [comment]
Yeah, for sure. You can use your team lead powers to bump own stuff as-well for similar issues :)
