### ISSUE TITLE
Make Travis less verbose

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-elm-starter#155]
@AronNovak Travis is quite chatty, I wonder if it's easily controllable?

![job__2733_3_-_gizra_circuit-bid_-_travis_ci_and_page_js_ __users_itama_sites_circuit-bid_client](https://user-images.githubusercontent.com/125707/28812951-d7cad81c-769f-11e7-8997-431869258ac3.jpg)

**Comment by AronNovak** [comment]
I am sure we can mute somehow one of the docker compose components, but it would be harmful, i think.
https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#more-configuration-parameters - here i did not see any way to decrease the verbosity, there's  `--debugEnabled`, but we don't enable it. I will see later if there's an easy solution for this.

**Comment by amitaibu** [comment]
Yeah, not a big issue. Lets also park it until we'd have a chance to explore a more native headless chrome approach

**Comment by AronNovak** [comment]
Closing in favor of #164 and #160
