### ISSUE TITLE
Use core patch to Improve WebTestCase performance [4h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-elm-starter#170]
https://www.drupal.org/node/2759197#comment-11385805

The folks in backdrop are using it, and their entire core test suite runs in under 4 minutes (8 in total, including the setup)

**Comment by AronNovak** [comment]
That was a pretty cool idea, I must say, big gain with minimal risk!

**Comment by AronNovak** [comment]
And it remains very useful when native Travis execution lands.
