### ISSUE TITLE
Move Config.elm into a config file

### ISSUE THREAD

**Issue by DavidHernandez** [Gizra/drupal-elm-starter#22]
As each person has a different local environment, is common to modify your local Config.elm, but as it is a versioned file, it forces to do and undo those modifications.

So, I will try to move that file into a configuration file and add a task on Gulp that creates the Config.elm file if the file does not exist.

**Comment by amitaibu** [comment]
We now have LocalConfig.elm - https://github.com/Gizra/drupal-elm-starter/blob/master/client/README.md#installation
