### ISSUE TITLE
Drupal 8 variant - server-side [6h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/drupal-elm-starter#221]
With:
 - DDEV
 - WDIO
 - Shellcheck
 - SimpleTest
 - Elm app - out of scope, to be added later

**Comment by AronNovak** [comment]
^^ @amitaibu Soon I start a new branch based on our recent project here. What do you think about the Elm part? Should it be a standalone frontend or should we have an embedded app in our starter kit?

**Comment by amitaibu** [comment]
For now Elm can be left out completely. @anvmn has already lots of experience with integrating Elm with 0.19, so we could later add the SPA app.

**Comment by AronNovak** [comment]
@amitaibu Ok, so I reduced the scope then.
