### ISSUE TITLE
Add WebdriverIO tests and Travis

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-elm-starter#29]

**Comment by amitaibu** [comment]
@ordavidil test is now in, so you can wire travis in this repo (it's public, so no Travis queues).

note that for locally you'll might need to `npm install` again from the `client` directory. Follow instructions on the [READEME](https://github.com/Gizra/drupal-elm-starter/tree/df04c962c55760f55b31b3563b15787aadc2ff19/client#webdriverio-tests)

**Comment by DavidHernandez** [comment]
I think this issue can be already closed as the PRs are merged and we already have WDIO tests on Travis.
