### ISSUE TITLE
Browser history doesn't affect the app

### ISSUE THREAD

**Issue by ordavidil** [Gizra/drupal-elm-starter#38]
Not sure is this is a bug in this app or in Elm.

When I click _back_ in the browser the url is being changed but the page doesn't change.

* Here is the page of item no. 2:
![elm](https://cloud.githubusercontent.com/assets/5985683/22436588/67828a66-e72d-11e6-903f-fbfb96911a51.gif)

* when going back in the browser, this is the result:
![elm](https://cloud.githubusercontent.com/assets/5985683/22436625/8bd2712e-e72d-11e6-8131-ec116d369084.gif)

**Comment by amitaibu** [comment]
@rgrempel care to have a look?
