### ISSUE TITLE
Overview of Pros / Cons for use in Production websites

### ISSUE THREAD

**Issue by mccrodp** [Gizra/drupal-elm-starter#40]
Hey,

This looks great and interested in experimenting with it and evaluating Elm for a potential client project.

Firstly, I noticed that the server here is D7, is there any reason D7 was chosen over D8, is there some D8 limitation? What is involved in getting this working with D8 as the backend?

Is this built for single page apps or do you think it (or headless with Elm front-end) is suitable is it for bigger / more complex websites? What limitation / benefits do you see at the moment in this setup and what areas are lacking contribution?

I've taken a look at some of the Blog posts from quite a while ago on the topic and wondering now with extra experience in the area, how things have changed since the below:

* http://www.gizra.com/content/thinking-choosing-elm/
* http://www.gizra.com/content/elmlang-headless-drupal/

Thanks!

**Comment by amitaibu** [comment]
> Firstly, I noticed that the server here is D7, is there any reason D7 was chosen over D8, is there some D8 limitation?

Yes, I find that our RESTful needs are better answered with RESTful for D7. easier control on the endpoints, access token, uploading files, etc'

> Is this built for single page apps

Yes, but also for complex SPAs. This repo is consolidation of the knowledge we have gained.

**Comment by mccrodp** [comment]
>Yes, I find that our RESTful needs are better answered with RESTful for D7. easier control on the endpoints, access token, uploading files, etc'

Very interesting, wondering if that is D7 v.s D8 in general or the RESTful module for D8 not having progressed as far, as it's not been around as long.

>Yes, but also for complex SPAs. This repo is consolidation of the knowledge we have gained.
Awesome, but perhaps for the front-end of a website, rather than an SPA, it might be overkill or become tricky to maintain?! Wonder if this "progressive decoupling" concept is worth exploring in terms of Elm, for websites rather than SPAs.

Looking forward to giving this a try sometime I have requirement to build an SPA. Thanks for sharing!

Going to re-vamp my yoga site with simple static content, Elm front-end w/ Bootsrap theme soon anyways. Elm looking good to me :)

**Comment by mccrodp** [comment]
@amitaibu, had you considered or tried using GraphQL module instead for D8?

**Comment by amitaibu** [comment]
I haven't looked at it in some time now. I'm mostly following JSON API. Once we'll have "easier control on the endpoints, access token, uploading files" I'd be happy to move to D8.

**Comment by amitaibu** [comment]
but I don't feel limited at all with the current D7 - we're able to spin up so really fun headless sites with it. It's stable and mature.

**Comment by mccrodp** [comment]
Sounds great and from the look of it, perhaps GraphQL isn't so stable / full featured yet, as they started a new 3.x branch. JSON API looks good, thanks, will keep an eye on that.

Have a potential site with OG or Group, so debating D7/D8, fully headless, standard site, or progressively decoupled (something like this [React w/ D8](https://github.com/skippednote/react-drupal)). Need to do more research v.s. requirements, this has been a really great help 👍

**Comment by mccrodp** [comment]
>we're able to spin up so really fun headless sites with it.

What about where SEO is concerned for non SPAs, can you choose to build on server as you would in React?

**Comment by amitaibu** [comment]
No server side render. Our SPAs are always behind user login - so SEO is not a concern.

**Comment by mccrodp** [comment]
>No server side render.

Good to know, thanks! It won't work in this case, but it the case you mention I'm hoping for an opportunity to give it a go.

I'm not sure there any Drupal solution for "Progressive Decoupling" module with ability for server side rendering at the moment. The PDB module has it on it's roadmap, but everything seems Angular first in the Drupal world at the moment and we're leaning towards the React end of things. Looks promising though (pdb) for site where SEO is concerned.
