### ISSUE TITLE
WDIO giving random fails

### ISSUE THREAD

**Issue by DavidHernandez** [Gizra/drupal-elm-starter#60]
On a PR I've workend on, I'm seeing WDIO returning random errors and I'm not sure why. Usually, after restarting the job, it successfully finishes. The PR should not break any WDIO, as it only touches the README.md file: #58 

Sample log of a failing test:

```
server.local_1  | [14:28:39]  COMMAND	POST 	 "/wd/hub/session/23855222-b2e0-4164-a3a5-0c28d278be6e/elements"
server.local_1  | [14:28:39]  DATA		{"using":"css selector","value":".login .ui.error.message"}
server.local_1  | [14:28:39]  RESULT		[{"ELEMENT":"3"}]
server.local_1  | [14:28:39]  COMMAND	GET 	 "/wd/hub/session/23855222-b2e0-4164-a3a5-0c28d278be6e/element/3/displayed"
server.local_1  | [14:28:39]  DATA		{}
server.local_1  | [14:28:39]  COMMAND	POST 	 "/wd/hub/session/23855222-b2e0-4164-a3a5-0c28d278be6e/elements"
server.local_1  | [14:28:39]  DATA		{"using":"css selector","value":".menu h4"}
server.local_1  | [14:28:39]  RESULT		true
server.local_1  | Unhandled rejection RequestError: Error: no auth mechanism defined
server.local_1  |     at new RequestError (/var/www/html/Server/client/node_modules/request-promise-core/lib/errors.js:14:15)
server.local_1  |     at Request.plumbing.callback (/var/www/html/Server/client/node_modules/request-promise-core/lib/plumbing.js:87:29)
server.local_1  |     at Request.RP$callback [as _callback] (/var/www/html/Server/client/node_modules/request-promise-core/lib/plumbing.js:46:31)
server.local_1  |     at self.callback (/var/www/html/Server/client/node_modules/request/request.js:186:22)
server.local_1  |     at emitOne (events.js:90:13)
server.local_1  |     at Request.emit (events.js:182:7)
server.local_1  |     at Auth.onRequest (/var/www/html/Server/client/node_modules/request/lib/auth.js:133:18)
server.local_1  |     at Request.auth (/var/www/html/Server/client/node_modules/request/request.js:1270:14)
server.local_1  |     at Request.init (/var/www/html/Server/client/node_modules/request/request.js:379:10)
server.local_1  |     at Request.RP$initInterceptor [as init] (/var/www/html/Server/client/node_modules/request-promise-core/configure/request2.js:45:29)
server.local_1  |     at new Request (/var/www/html/Server/client/node_modules/request/request.js:128:8)
server.local_1  |     at request (/var/www/html/Server/client/node_modules/request/index.js:54:10)
server.local_1  |     at BrowserstackService._update (/var/www/html/Server/client/node_modules/wdio-browserstack-service/build/browserstack-service.js:15:3)
server.local_1  |     at BrowserstackService.after (/var/www/html/Server/client/node_modules/wdio-browserstack-service/build/browserstack-service.js:11:8)
server.local_1  |     at execHook (/var/www/html/Server/client/node_modules/wdio-sync/build/index.js:259:35)
server.local_1  | [14:28:39]  RESULT		[]
server.local_1  | [14:28:39]  COMMAND	DELETE 	 "/wd/hub/session/23855222-b2e0-4164-a3a5-0c28d278be6e"
server.local_1  | [14:28:39]  DATA		{}
server.local_1  | [14:28:39]  RESULT		null
server.local_1  | ------------------------------------------------------------------
server.local_1  | [chrome #0-0] Session ID: 23855222-b2e0-4164-a3a5-0c28d278be6e
server.local_1  | [chrome #0-0] Spec: /var/www/html/Server/client/test/specs/login.js
server.local_1  | [chrome #0-0] Running: chrome
server.local_1  | [chrome #0-0]
server.local_1  | [chrome #0-0]   login page
server.local_1  | [chrome #0-0]
server.local_1  | [chrome #0-0]   login page
server.local_1  | [chrome #0-0]       1) should allow a user to login
server.local_1  | [chrome #0-0]       ✓ should not allow an anonymous user with wrong credentials to login
server.local_1  | [chrome #0-0]
server.local_1  | [chrome #0-0]
server.local_1  | [chrome #0-0] 1 passing (12s)
server.local_1  | [chrome #0-0] 1 failing
server.local_1  | [chrome #0-0]
server.local_1  | [chrome #0-0] 1) login page should allow a user to login:
server.local_1  | [chrome #0-0] Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
server.local_1  | [chrome #0-0] Error: Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
server.local_1  | [chrome #0-0]     at Timeout.<anonymous> (/var/www/html/Server/client/node_modules/mocha/lib/runnable.js:232:19)
server.local_1  | [chrome #0-0]     at tryOnTimeout (timers.js:224:11)
server.local_1  | [chrome #0-0]     at Timer.listOnTimeout (timers.js:198:5)
server.local_1  | [chrome #0-0]
server.local_1  | 
dockerfiles_server.local_1 exited with code 1
Aborting on container exit...
Stopping dockerfiles_hub_1 ... 
The command "$TRAVIS_BUILD_DIR/ci-scripts/test_server.sh" exited with 1.
cache.2
store build cache
0.00s
1.54schanges detected, packing new archive
uploading archive
```

**Comment by ordavidil** [comment]
maybe @AronNovak can help in here

**Comment by AronNovak** [comment]
Yes. i need to work on it more then, almost certainly it's a timing issue, sometimes things happen quickly enough, sometimes not. I had such a case for gulp vs WDIO already, as gulp was started async, and it was too slow to complete before WDIO started, at local, i had no such issue, so i suspect something similar, i will work on this to figure it out.

**Comment by ordavidil** [comment]
if one task is dependent on a different one then maybe we can implement some kind of a priority queue.

**Comment by AronNovak** [comment]
Yep, that's definitely a way to go for timing issues. This one is happening entirely inside WDIO, so my plan for now is to check the result of repeated executions with different timeouts and try to narrow down the place where instead of a timeout, we need something smarter.

**Comment by AronNovak** [comment]
To have a good sense of this, i spin up a trial VPS at CloudSigma with this:
```
cloudsigma@Debian-Server-8-7:~$ crontab -l | tail -n 2
# m h  dom mon dow   command
*/20 * * * * /home/cloudsigma/drupal-elm-starter/test.sh
```

And:
```
cloudsigma@Debian-Server-8-7:~$ cat drupal-elm-starter/test.sh 
/home/cloudsigma/drupal-elm-starter
cd ci-scripts/docker_files
export BUILD_WEBDRIVERIO=1
docker-compose up >> /tmp/compose.log
```

By tomorrow, i will have a better understanding of the stability.

**Comment by AronNovak** [comment]
Eh, unfortunately I do not have any results by tomorrow morning, that machine disappeared, what you pay is what you get..., i restarted the whole procedure at Linode.

**Comment by AronNovak** [comment]
At a separate VPS, the test seems to be quite stable:
```
ubuntu@ubuntu:~$ cat /tmp/compose.log | grep "2 passing" | wc -l
126
ubuntu@ubuntu:~$ cat /tmp/compose.log | grep passing | wc -l
126
ubuntu@ubuntu:~$ cat /tmp/compose.log | grep failing | wc -l
0
ubuntu@ubuntu:~$ crontab -l | tail -n 2
# m h  dom mon dow   command
*/20 * * * * /home/ubuntu/drupal-elm-starter/test.sh
```

But I could also see myself unexpected failures on Travis.
It needs further investigation then, also why it uses timeout of 10000 ms, when the configfile specifies a greater value.

**Comment by AronNovak** [comment]
Some more updates, as it's really Travis specific:
On Travis SSH debug session, sometimes it succeeds, sometimes it's not, i checked the memory consumption in the meantime and it did not cross 1.6-2G from the available 7.5, so definitely we don't run out of memory there, neither from disk space:
```
/dev/sda1        30G   20G  9.2G  68% /
```

**Comment by amitaibu** [comment]
I'm not 100% it Travis specific. If you run this locally, does it always pass?

**Comment by AronNovak** [comment]
Well, I am not 100% sure either, we can only say it after we could locate the root cause. But yes, locally it did always pass (for me) and on a Linode VPS, it passed 126 times in a row, without any erroneous runs.

**Comment by amitaibu** [comment]
I think what could help is getting the HTML output of the page -- so you could see what WDIO is "seeing" (Or even better, try to view the chrome with VNC)

**Comment by amitaibu** [comment]
My guess is that wdio might be starting too early, where gulp has finished yet.

**Comment by AronNovak** [comment]
We already eliminated that race condition between wdio and gulp, right now i am looking to https://uploadcare.com/ to upload all the screenshots what we made during the execution, but yes, HTML output would be helpful too, but based on my understanding, we already do very helpful screenshots, we just need to expose them somehow.

**Comment by AronNovak** [comment]
For some reason, we have no screenshots at Travis, possibly some limitation of the Chromedriver, anyways, I used https://github.com/elgalu/docker-selenium#record-videos option to record the full video, no luck yet. When I could catch an erroneous run at Travis, on the video, I could not see the start of Chrome, despite that one of the tests passed, so it's sure that it was running, possibly the recording ended too early, i will follow on this path to be able to see the full video of a bogus test run.

**Comment by amitaibu** [comment]
The video recording sounds like a great path!

**Comment by AronNovak** [comment]
As a tiny step, I checked, via VNC, docker-compose config at localhost allowed me to see Chrome's window. Next step: debug the video-recording at localhost for a much simpler test, where no wait is involved essentially.

**Comment by AronNovak** [comment]
Hm, i recorded a video at localhost (only 4 FPS to decrease the pressure), I could not see anything in the video player. after I extracted all the frames into images, I could spot the frames with the browser:

![vid435](https://cloud.githubusercontent.com/assets/114076/23906993/001045fc-08d0-11e7-890e-93108519ae72.png)

The next step is to tune / postprocess in a video in that way that we have a material which is consumable by humans, out of the box.

**Comment by amitaibu** [comment]
Nice. But, if it would have been e.g. 24fps, then you'd see it more easily, no?

**Comment by AronNovak** [comment]
With the linked PR's merge, it's closed, further related issues exist to improve WDIO tests.
