### ISSUE TITLE
Video recording for WDIO [8h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/drupal-elm-starter#83]
Current status:
WDIO tests are executed by Travis, step-by-step, random failure of specs is allowed.

Todo:
 - [x] Switch to https://github.com/zalando/zalenium and configure the recording
 - [x] Upload it to Github/Google drive
 - [ ] Post a comment to the issue

**Comment by AronNovak** [comment]
The video recording part works perfectly out of the box:
https://drive.google.com/open?id=0B7FpNcQYpf7GSXdpU0hqMF9YOFE
As only the actual test is recorded, the video size is quite reasonable.

**Comment by AronNovak** [comment]
For the upload part, I looked around.
https://github.com/prasmussen/gdrive - for Google Drive, it seems to be the best, but to machine 2 machine communication, it requires paid Google Compute account / API access.
However Vimeo would allow to upload 500 Mb per week. Waiting for the approval of the account from Vimeo to be able to programmatically upload videos.

**Comment by AronNovak** [comment]
Hm, with those video sizes, we could even consider uploading it as a GH comment attachment, especially if we reduce the resolution.

**Comment by amitaibu** [comment]
>  it requires paid Google Compute account / API access.

We have that (for Shoov), so it shouldn't be problematic.

**Comment by amitaibu** [comment]
> Hm, with those video sizes, we could even consider uploading it as a GH comment attachment

You mean as gif?

**Comment by AronNovak** [comment]
Hm, It would be a bit strange to re-encode the video, for we could ZIP the MP4 however.

**Comment by amitaibu** [comment]
👍

**Comment by AronNovak** [comment]
Google Drive upload is automated:
![upload](https://cloud.githubusercontent.com/assets/114076/24455825/491b423e-1491-11e7-92d5-859273685f7c.png)

I crafted the basic Travis part using `encrypt-file`, need to iron out in the coming days. Also it should upload videos only on failure, also only the failed specs, it's still do be done.

**Comment by amitaibu** [comment]
> Google Drive upload is automated

That great. In that case We shouldn't zip the video, as what's nice with GDrive is that it gives you automatically a youTube like video player.

**Comment by AronNovak** [comment]
Yep, for sure, for Google Drive, no zipping. For your information, I discarded the GitHub comment file attachment way, as I could not find any evidence that this operation is supported by their API.

**Comment by amitaibu** [comment]
https://developer.github.com/v3/issues/comments/#create-a-comment

**Comment by AronNovak** [comment]
Indeed, and the only parameter is the body, which cannot hold binary, or do i miss something?

**Comment by amitaibu** [comment]
Sorry - I mean, yeah - upload video to GDrive -- and add the link they give us as a comment

**Comment by AronNovak** [comment]
Via Travis, now the video upload works well:
![upload](https://cloud.githubusercontent.com/assets/114076/24493501/4e564f20-152f-11e7-9a42-b7638ccb9024.png)

The next steps are:
 - GitHub comment
 - make sure the output status is indeed proper in case of a failure
 - no shell warnings are outputted

**Comment by AronNovak** [comment]
https://drive.google.com/file/d/0B4uFEYHNgo60YWl0VC1mSnAwSWM/view?usp=drivesdk
And the first video that was uploaded by Travis, without any human interaction.

**Comment by AronNovak** [comment]
https://github.com/gizra-robot - he will comment for us on GH

**Comment by AronNovak** [comment]
About posting a GH comment:
Travis provides us the branch name only, it seems: https://github.com/travis-ci/travis-ci/issues/6652#issuecomment-255597049

GitHub provides an API to:
 - list pull requests of a repository, get details - https://api.github.com/repos/Gizra/drupal-elm-starter/pulls , https://api.github.com/repos/Gizra/drupal-elm-starter/pulls/84
 - list branches, get details: https://api.github.com/repos/Gizra/drupal-elm-starter/branches/83-video

So the way to go would be to get issue/PR number from https://api.github.com/repos/Gizra/drupal-elm-starter/pulls?head=83-video (or similarly) , then post the comment.
